name: Docker

on:
  # Once a week
  schedule:
    - cron: '0 0 * * 0'
  push:
    paths:
      - 'Dockerfile'
      - 'config.toml'
      - '.github/workflows/docker-image.yml'
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - '**'
    paths:
      - 'Dockerfile'
      - 'config.toml'
      - '.github/workflows/docker-image.yml'
  workflow_dispatch:
    inputs:
      rustc_version:
        description: 'Rust version'
        required: false
        default: ''
        type: string

env:
  IMAGE_NAME: douman/rust-musl
  DOCKER_REGISTRY: docker.io
  GITHUB_REGISTRY: ghcr.io
  DOCKER_IMAGE_NAME: douman/rust-musl
  GITHUB_IMAGE_NAME: doumanash/rust-musl

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: arm64

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v4

      - name: Log into ${{ env.DOCKER_REGISTRY }} registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: douman
          ## Set in repo Settings->Secrets->New repository secret
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log into ${{ env.GITHUB_REGISTRY }} registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v4
        with:
          registry: ${{ env.GITHUB_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and test Docker image
        id: build-docker
        uses: docker/build-push-action@v7
        with:
          context: .
          build-args: "RUST_VERSION=${{ inputs.rustc_version || 'stable' }}"
          platforms: linux/amd64
          load: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Test
        id: test
        run: |
          echo '## Build docker ${{ inputs.rustc_version || 'stable' }} image 🚀' >> $GITHUB_STEP_SUMMARY
          VERSION=$(docker run --rm ${{ env.IMAGE_NAME }} rustc --version | cut -d" " -f2)
          echo "rustc_version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "- Rustc version: $VERSION" >> $GITHUB_STEP_SUMMARY
          VERSION=$(echo "$VERSION" | cut -d"." -f 1,2)
          echo "rustc_short_version=$VERSION" >> "$GITHUB_OUTPUT"
          VERSION=$(docker run --rm ${{ env.IMAGE_NAME }} cat /etc/alpine-release | cut -d"." -f 1,2)
          echo "alpine_version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "- Alpine version: $VERSION" >> $GITHUB_STEP_SUMMARY

      - name: Push ${{ inputs.rustc_version }} image
        if: inputs.rustc_version != ''
        id: push-version-docker
        uses: docker/build-push-action@v7
        with:
          context: .
          build-args: "RUST_VERSION=${{ inputs.rustc_version || 'stable' }}"
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}-alpine${{ steps.test.outputs.alpine_version }}
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}-alpine${{ steps.test.outputs.alpine_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}-alpine${{ steps.test.outputs.alpine_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}-alpine${{ steps.test.outputs.alpine_version }}

      - name: Push latest stable image
        if: inputs.rustc_version == ''
        id: push-stable-docker
        uses: docker/build-push-action@v7
        with:
          context: .
          build-args: "RUST_VERSION=${{ inputs.rustc_version || 'stable' }}"
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:latest
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}-alpine${{ steps.test.outputs.alpine_version }}
            ${{env.DOCKER_REGISTRY}}/${{ env.DOCKER_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}-alpine${{ steps.test.outputs.alpine_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:latest
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_version }}-alpine${{ steps.test.outputs.alpine_version }}
            ${{env.GITHUB_REGISTRY}}/${{ env.GITHUB_IMAGE_NAME }}:${{ steps.test.outputs.rustc_short_version }}-alpine${{ steps.test.outputs.alpine_version }}
